<?php
/**
 * BULK HOMME - Logo Template
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
$logoSrc = $block->getLogoSrc();
$logoAlt = $block->getLogoAlt();
$logoWidth = $block->getLogoWidth();
$logoHeight = $block->getLogoHeight();
?>

<a href="<?= $block->escapeUrl($block->getUrl('')) ?>" 
   title="<?= $block->escapeHtmlAttr($logoAlt) ?>" 
   class="logo">
    <img src="<?= $block->escapeUrl($logoSrc) ?>" 
         alt="<?= $block->escapeHtmlAttr($logoAlt) ?>"
         <?php if ($logoWidth): ?>
         width="<?= $block->escapeHtmlAttr($logoWidth) ?>"
         <?php endif; ?>
         <?php if ($logoHeight): ?>
         height="<?= $block->escapeHtmlAttr($logoHeight) ?>"
         <?php endif; ?>
    />
</a>
