<?php
/**
 * BULK HOMME - Copyright
 *
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<div class="copyright">
    <p>&copy; <?= $block->escapeHtml(date('Y')) ?> <?= $block->escapeHtml(__('BULK HOMME. All rights reserved.')) ?></p>
    <p>
        <a href="<?= $block->escapeUrl($block->getUrl('privacy-policy')) ?>"><?= $block->escapeHtml(__('Privacy Policy')) ?></a>
        |
        <a href="<?= $block->escapeUrl($block->getUrl('terms-conditions')) ?>"><?= $block->escapeHtml(__('Terms & Conditions')) ?></a>
    </p>
</div>
